namespace RavensPort.Core.Models;

public sealed class AppSettings
{
    public int ListenPort { get; set; } = 5559;

    /// <summary>
    /// Master switch for the MCP funnel endpoints under /mcp. Off by default: the funnel lets a
    /// caller reach several upstreams (and their attached OAuth grants) through one path, so it
    /// stays dark until the user asks for it rather than appearing on upgrade.
    /// </summary>
    public bool McpFunnelEnabled { get; set; }

    /// <summary>
    /// If true, the proxy and funnel routes require a client certificate for authentication.
    /// Kestrel binds to https://127.0.0.1 and enforces client certificate validation.
    /// </summary>
    public bool MtlsEnabled { get; set; }

    /// <summary>
    /// The Base64 encoded PFX string for the mTLS client certificate generated by the UI.
    /// </summary>
    public string MtlsClientCertificatePfx { get; set; } = "";

    /// <summary>
    /// The password <see cref="MtlsClientCertificatePfx"/> is encrypted with. Always a password the
    /// user typed on the Settings tab: nothing in this app mints a certificate under a password of
    /// its own, so there is no value here that RavensPort itself chose.
    ///
    /// Empty is not "no password" and no longer resolves to one. It marks a store written before
    /// this field existed, whose certificate carries a built-in password that this build no longer
    /// knows — so that blob cannot be opened, mTLS does not come up, and the log and the Settings
    /// tab both say to generate a new certificate. That is a one-time cost at upgrade, paid by
    /// regenerating and reinstalling on every client that calls the proxy.
    ///
    /// It lives here because the app has to re-read its own certificate unattended at every start,
    /// so a password it cannot recover is a password that locks the proxy out of its own listener.
    /// The vault this is written to is the same one holding the OAuth refresh tokens.
    /// </summary>
    public string MtlsClientCertificatePassword { get; set; } = "";

    // There is deliberately no proxy-wide API key here. Authentication is per endpoint: every
    // route and every funnel carries its own <see cref="ProxyKey"/>, so a key leaked from one
    // client cannot spend the OAuth grant attached to a different route, and revoking one client
    // is a single-endpoint operation rather than a re-key of everything.
}
