namespace RavensPort.Core.Vault;

/// <summary>
/// Keeps RavensPort's Proton Pass session key on this machine, so that a restart does not mean
/// signing in through a browser again.
///
/// The key is generated by RavensPort, never shown to the user and never typed by them, so losing
/// it means losing the session — which is why it is kept at all, and why the way it is kept is a
/// security decision rather than a storage detail.
///
/// **The platforms differ, and not only in mechanism.** On Windows,
/// <see cref="HelloKeyProtector"/> binds the key to a Windows Hello gesture: the gesture is not a
/// check in front of the decryption, it produces the key that performs it, so there is no branch
/// an attacker can skip. On Linux the key goes into the system keyring, which encrypts at rest but
/// is normally unlocked at login — so anything running as the same user can read it without
/// prompting anyone.
///
/// That difference is real and the UI is required to say so. Whatever presents this to the user
/// must describe the guarantee of the implementation actually in use; reusing the Hello wording
/// elsewhere would promise something that is not being delivered.
/// </summary>
public interface ISessionKeyProtector
{
    /// <summary>
    /// Whether this machine can protect a key at all. False means the sign-in flow must not offer
    /// to keep the session, because a key stored now could not be recovered later.
    /// </summary>
    Task<bool> IsAvailableAsync();

    /// <summary>Whether a key is already being held for this session directory.</summary>
    bool HasProtectedKey(string sessionDirectory);

    /// <summary>
    /// Stores the key. Must throw if it cannot — a caller told this succeeded will let the user
    /// believe their session survives a restart when it does not.
    /// </summary>
    Task ProtectAsync(string sessionDirectory, string sessionKey);

    /// <summary>
    /// Returns the key, or null when there is none to return. Failing to unlock — a cancelled
    /// prompt, a locked keyring, a key that no longer opens — throws, because "no key stored" and
    /// "would not give it to us" lead the user to different places.
    /// </summary>
    Task<string?> UnprotectAsync(string sessionDirectory);

    /// <summary>Discards the stored key. Must not throw when there was nothing to discard.</summary>
    Task ForgetAsync(string sessionDirectory);
}
